services:
  - type: web
    name: TIHub
    env: python
    region: oregon
    plan: free
    branch: main
    rootDirectory: backend   # backend is where Flask lives
    buildCommand: |
      # Install backend dependencies
      pip install -r requirements.txt
      
      # Build frontend
      cd ../frontend
      npm install
      npm run build
      cd ../backend
    startCommand: |
      # Use Flask production server
      export FLASK_APP=app:create_app
      export FLASK_ENV=production
      flask run --host=0.0.0.0 --port=$PORT
    envVars:
      - key: SECRET_KEY
        fromDatabase: true
      - key: MONGO_URI
        fromDatabase: true
